[build]
  command = "npm run build"
  publish = "dist"
[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200